export const IPC = {
  VOICE_STATE_CHANGED: 'voice:state-changed',
  VOICE_START: 'voice:start',
  VOICE_STOP: 'voice:stop',
  VOICE_INTERRUPT: 'voice:interrupt',
  AUDIO_CHUNK: 'audio:chunk',
  AUDIO_LEVEL: 'audio:level',
  CHAT_SEND: 'chat:send',
  CHAT_MESSAGE: 'chat:message',
  CHAT_STREAM: 'chat:stream',
  CHAT_HISTORY: 'chat:history',
  TTS_AUDIO: 'tts:audio',
  TTS_STOP: 'tts:stop',
  KEYS_GET: 'keys:get',
  KEYS_SET: 'keys:set',
  KEYS_READ_OPENCLAW: 'keys:read-openclaw',
  KEYS_READ_ENV: 'keys:read-env',
  KEYS_VALIDATE: 'keys:validate',
  CONFIG_GET: 'config:get',
  CONFIG_SET: 'config:set',
  CONNECTION_STATUS: 'connection:status',
} as const
